
import React from 'react';
import { Tool } from './types.ts';

export const TOOLS_DATA: Partial<Tool>[] = [
  { 
    id: 'qr-gen', 
    name: 'QR Code Generator', 
    slug: 'qr-code-generator', 
    category: 'Utility', 
    icon: 'fa-qrcode', 
    description: 'Generate high-definition QR codes for URLs, text, and business cards.', 
    seoTitle: 'QR Code Generator | Toolly.online', 
    seoDescription: 'Create high-quality QR codes instantly for free. Custom colors and download options.', 
    keywords: ['qr', 'generator', 'code', 'online'],
    tutorial: '1. Enter your target URL or message in the input field. 2. Customize colors if desired. 3. The QR code updates automatically. 4. Click Download PNG to save it.',
    rating: 4.9,
    isPremium: false
  },
  { 
    id: 'ai-img', 
    name: 'AI Image Generator', 
    slug: 'ai-image-generator', 
    category: 'AI', 
    icon: 'fa-wand-magic-sparkles', 
    description: 'Transform your wildest ideas into stunning visuals with Gemini AI.', 
    seoTitle: 'AI Image Generator | Text to Image | Toolly.online', 
    seoDescription: 'Generate professional AI images from text prompts using the latest Gemini models.', 
    keywords: ['ai image', 'text to image', 'gemini ai', 'art generator'],
    tutorial: '1. Describe the image you want in detail. 2. Select an aspect ratio (1:1, 16:9, or 9:16). 3. Hit Generate and wait for the AI to create your masterpiece.',
    rating: 4.8,
    isPremium: true
  },
  { 
    id: 'json-format', 
    name: 'JSON Formatter', 
    slug: 'json-formatter', 
    category: 'Developer', 
    icon: 'fa-code', 
    description: 'Beautify, minify, and validate complex JSON data instantly.', 
    seoTitle: 'JSON Formatter & Validator | Toolly.online', 
    seoDescription: 'Online JSON formatter and validator with syntax highlighting and minify options.', 
    keywords: ['json formatter', 'json validator', 'beautify json'],
    tutorial: '1. Paste your raw JSON into the editor. 2. Use the "Beautify" buttons to indent code. 3. Use "Minify" to compress it. 4. Check for syntax errors in real-time.',
    rating: 4.7
  },
  { 
    id: 'pw-gen', 
    name: 'Password Generator', 
    slug: 'password-generator', 
    category: 'Utility', 
    icon: 'fa-key', 
    description: 'Create ultra-secure, uncrackable passwords for all your accounts.', 
    seoTitle: 'Secure Password Generator | Toolly.online', 
    seoDescription: 'Generate strong, secure passwords with custom lengths and character types.', 
    keywords: ['password generator', 'secure password', 'password tool'],
    tutorial: '1. Adjust the length slider (we recommend at least 16). 2. Toggle character sets like Symbols or Numbers. 3. Click Regenerate for a new set. 4. Click Copy to use it.',
    rating: 4.9
  },
  { 
    id: 'txt-speech', 
    name: 'Text to Speech', 
    slug: 'text-to-speech', 
    category: 'AI', 
    icon: 'fa-volume-high', 
    description: 'Convert any text into natural-sounding high-quality audio.', 
    seoTitle: 'AI Text to Speech Generator | Toolly.online', 
    seoDescription: 'Professional AI-powered text to speech tool with natural human-like voices.', 
    keywords: ['text to speech', 'tts', 'ai voice', 'speech generator'],
    tutorial: '1. Paste your script into the text area. 2. Click "Listen Now" to generate audio. 3. Ensure your volume is up. This tool uses premium Gemini TTS technology.',
    rating: 4.6,
    isPremium: true
  },
  { 
    id: 'word-count', 
    name: 'Word Counter', 
    slug: 'word-counter', 
    category: 'Text', 
    icon: 'fa-list-ol', 
    description: 'Analyze text length, reading time, and character statistics.', 
    seoTitle: 'Word & Character Counter | Toolly.online', 
    seoDescription: 'Count words, characters, sentences, and estimate reading time online.', 
    keywords: ['word count', 'character counter', 'reading time', 'text tool'],
    tutorial: '1. Type or paste your text. 2. View live statistics in the top bar. 3. Use "Clear All" to start fresh.',
    rating: 4.5
  },
  { 
    id: 'img-comp', 
    name: 'Image Compressor', 
    slug: 'image-compressor', 
    category: 'Media', 
    icon: 'fa-file-image', 
    description: 'Optimize images for the web without losing visible quality.', 
    seoTitle: 'Online Image Compressor | JPG & PNG | Toolly.online', 
    seoDescription: 'Compress images to reduce file size while maintaining excellent quality.', 
    keywords: ['compress image', 'optimize photo', 'reduce image size'],
    tutorial: '1. Upload an image (JPG, PNG, WebP). 2. Adjust the quality slider. 3. Click "Compress Now". 4. Download your optimized file.',
    rating: 4.8
  },
  { 
    id: 'color-picker', 
    name: 'Color Picker', 
    slug: 'color-picker', 
    category: 'Developer', 
    icon: 'fa-eye-dropper', 
    description: 'Find perfect colors and convert between HEX, RGB, and HSL.', 
    seoTitle: 'Advanced Color Picker & Converter | Toolly.online', 
    seoDescription: 'Online color picker tool for developers and designers with shade generation.', 
    keywords: ['color picker', 'hex to rgb', 'hsl converter', 'web design'],
    tutorial: '1. Use the color selection box or type a HEX code. 2. View different values below. 3. Click any value to copy it to your clipboard.',
    rating: 4.7
  },
  { 
    id: 'lorem-gen', 
    name: 'Lorem Ipsum Generator', 
    slug: 'lorem-ipsum-generator', 
    category: 'Text', 
    icon: 'fa-font', 
    description: 'Generate high-quality placeholder text for your designs.', 
    seoTitle: 'Lorem Ipsum Placeholder Text Generator | Toolly.online', 
    seoDescription: 'Generate paragraphs, sentences, or words of placeholder text instantly.', 
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text'],
    tutorial: '1. Select the amount of text you need. 2. Choose between words, sentences, or paragraphs. 3. Click Generate then Copy.',
    rating: 4.4
  },
  { 
    id: 'md-editor', 
    name: 'Markdown Editor', 
    slug: 'markdown-editor', 
    category: 'Text', 
    icon: 'fa-file-pen', 
    description: 'A professional live-preview editor for Markdown files.', 
    seoTitle: 'Online Markdown Editor with Live Preview | Toolly.online', 
    seoDescription: 'Write and preview Markdown in real-time. Minimalist and distraction-free.', 
    keywords: ['markdown editor', 'md viewer', 'markdown preview'],
    tutorial: '1. Write your markdown in the left pane. 2. See the rendered output on the right. 3. Standard syntax like # for headers is supported.',
    rating: 4.6
  },
  { 
    id: 'b64-tool', 
    name: 'Base64 Encoder/Decoder', 
    slug: 'base64-encoder-decoder', 
    category: 'Developer', 
    icon: 'fa-shield-halved', 
    description: 'Convert strings to Base64 and back with high precision.', 
    seoTitle: 'Base64 Encoder & Decoder | Toolly.online', 
    seoDescription: 'Fast and secure Base64 conversion tool for developers.', 
    keywords: ['base64', 'encode', 'decode', 'binary to text'],
    tutorial: '1. Select "Encode" or "Decode" mode. 2. Paste your content. 3. The result appears below automatically.',
    rating: 4.3
  },
  { 
    id: 'stopwatch', 
    name: 'Stopwatch / Timer', 
    slug: 'stopwatch-timer', 
    category: 'Utility', 
    icon: 'fa-stopwatch', 
    description: 'Precision timing for productivity and tasks.', 
    seoTitle: 'Online Stopwatch & Precision Timer | Toolly.online', 
    seoDescription: 'Simple and accurate online stopwatch for tracking time.', 
    keywords: ['stopwatch', 'timer', 'clock', 'online timer'],
    tutorial: '1. Click "Start" to begin. 2. Use "Stop" to pause. 3. "Reset" clears the time back to zero.',
    rating: 4.5
  },
  { 
    id: 'ip-info', 
    name: 'IP & Device Info', 
    slug: 'ip-device-info', 
    category: 'Utility', 
    icon: 'fa-globe', 
    description: 'Get deep insights into your network connection and hardware.', 
    seoTitle: 'My IP & Device Information Tool | Toolly.online', 
    seoDescription: 'Find your IP address, ISP, location, and device details instantly.', 
    keywords: ['my ip', 'device info', 'isp checker', 'user agent'],
    tutorial: '1. Open the tool. 2. Your information is fetched automatically and displayed securely.',
    rating: 4.7
  },
  { 
    id: 'html-min', 
    name: 'HTML Minifier', 
    slug: 'html-minifier', 
    category: 'Developer', 
    icon: 'fa-file-code', 
    description: 'Compress your HTML files to the absolute minimum size.', 
    seoTitle: 'HTML Minifier & Compressor | Toolly.online', 
    seoDescription: 'Optimize website speed by minifying your HTML code for free.', 
    keywords: ['minify html', 'html compressor', 'web optimization'],
    tutorial: '1. Paste your HTML code. 2. Click Minify. 3. Copy the result. Comments and whitespaces are removed.',
    rating: 4.4
  },
  { 
    id: 'css-min', 
    name: 'CSS Minifier', 
    slug: 'css-minifier', 
    category: 'Developer', 
    icon: 'fa-scissors', 
    description: 'Shrink CSS stylesheets for lightning-fast page loads.', 
    seoTitle: 'CSS Minifier & Optimizer | Toolly.online', 
    seoDescription: 'Fast online CSS minification to improve site performance.', 
    keywords: ['minify css', 'css optimizer', 'reduce css size'],
    tutorial: '1. Paste your CSS. 2. Hit Minify. 3. Use the reduced code in your production builds.',
    rating: 4.4
  },
  { 
    id: 'js-min', 
    name: 'JS Minifier', 
    slug: 'js-minifier', 
    category: 'Developer', 
    icon: 'fa-file-js', 
    description: 'Professional JavaScript obfuscation and minification.', 
    seoTitle: 'JS Minifier & Compressor | Toolly.online', 
    seoDescription: 'Compress and minify JavaScript code for smaller file sizes.', 
    keywords: ['minify js', 'javascript compressor', 'js optimizer'],
    tutorial: '1. Input your script. 2. Click Minify. 3. The tool removes comments and extra spaces.',
    rating: 4.3
  },
  { 
    id: 'speech-txt', 
    name: 'Speech to Text', 
    slug: 'speech-to-text', 
    category: 'AI', 
    icon: 'fa-microphone', 
    description: 'Transcribe your voice into text in real-time.', 
    seoTitle: 'Online Speech to Text Transcription | Toolly.online', 
    seoDescription: 'Accurately transcribe audio to text using browser-based recognition.', 
    keywords: ['speech to text', 'dictation', 'voice typing'],
    tutorial: '1. Click "Start Recording". 2. Speak clearly into your microphone. 3. Watch the text appear instantly.',
    rating: 4.5,
    isPremium: false
  },
  { 
    id: 'img-pdf', 
    name: 'Image to PDF', 
    slug: 'image-to-pdf', 
    category: 'Media', 
    icon: 'fa-images', 
    description: 'Merge multiple image files into a professional PDF document.', 
    seoTitle: 'Convert Image to PDF Online | Toolly.online', 
    seoDescription: 'Combine JPG or PNG images into a single high-quality PDF file.', 
    keywords: ['image to pdf', 'jpg to pdf', 'png to pdf', 'merge to pdf'],
    tutorial: '1. Upload all the images you want in the PDF. 2. Review the list. 3. Click Generate PDF to merge and download.',
    rating: 4.7
  },
  { 
    id: 'notepad', 
    name: 'Online Notepad', 
    slug: 'online-notepad', 
    category: 'Utility', 
    icon: 'fa-note-sticky', 
    description: 'A safe, persistent space for your notes in the cloud.', 
    seoTitle: 'Free Online Notepad | No Login Required | Toolly.online', 
    seoDescription: 'Quick and easy browser-based notepad that saves automatically.', 
    keywords: ['online notepad', 'browser notes', 'sticky notes'],
    tutorial: '1. Start typing your notes. 2. They save automatically to your browser storage. 3. Use "Clear All" to delete.',
    rating: 4.8
  },
  { 
    id: 'emoji-conv', 
    name: 'Emoji Converter', 
    slug: 'emoji-converter', 
    category: 'Social', 
    icon: 'fa-face-smile', 
    description: 'Automatically replace keywords with relevant emojis.', 
    seoTitle: 'Text to Emoji Converter | Toolly.online', 
    seoDescription: 'Convert plain text into fun emoji-filled messages for social media.', 
    keywords: ['emoji converter', 'text to emoji', 'emoji mapping'],
    tutorial: '1. Type your message. 2. Keywords like "happy" or "fire" transform into emojis. 3. Copy and share!',
    rating: 4.2
  },
  { id: 'url-short', name: 'URL Shortener', slug: 'url-shortener', category: 'Utility', icon: 'fa-link', description: 'Create branded short links with analytics tracking.', seoTitle: 'URL Shortener | Toolly.online', seoDescription: 'Free short URL generator.', keywords: ['shorten url', 'tiny url'], rating: 4.6 },
  { id: 'pal-checker', name: 'Palindrome Checker', slug: 'palindrome-checker', category: 'Text', icon: 'fa-rotate-left', description: 'Check if words or phrases read the same backwards.', seoTitle: 'Palindrome Checker | Toolly.online', seoDescription: 'Verify palindromes instantly.', keywords: ['palindrome'], rating: 4.1 },
  { id: 'txt-reverse', name: 'Text Reverser', slug: 'text-reverser', category: 'Text', icon: 'fa-backward', description: 'Flip your text upside down or backwards.', seoTitle: 'Text Reverser Tool | Toolly.online', seoDescription: 'Reverse text strings instantly.', keywords: ['reverse text'], rating: 4.0 },
  { id: 'b64-img', name: 'Base64 Image Decoder', slug: 'base64-image-decoder', category: 'Developer', icon: 'fa-image', description: 'Turn Base64 strings into viewable image files.', seoTitle: 'Base64 to Image Decoder | Toolly.online', seoDescription: 'Convert data strings to images.', keywords: ['base64 to image'], rating: 4.5 },
  { id: 'pdf-comp', name: 'PDF Compressor', slug: 'pdf-compressor', category: 'Media', icon: 'fa-file-pdf', description: 'Reduce PDF size for easier sharing.', seoTitle: 'PDF Compressor | Toolly.online', seoDescription: 'Optimize PDF files.', keywords: ['compress pdf'], rating: 4.6 },
  { id: 'vid-mp3', name: 'Video to MP3', slug: 'video-to-mp3', category: 'Media', icon: 'fa-file-audio', description: 'Extract the soundtrack from any video file.', seoTitle: 'Video to MP3 Extractor | Toolly.online', seoDescription: 'Convert video to audio.', keywords: ['video to mp3'], rating: 4.7 },
  { id: 'web-shot', name: 'Website Screenshot', slug: 'website-screenshot', category: 'Utility', icon: 'fa-camera-retro', description: 'Take high-res screenshots of any website.', seoTitle: 'Web Screenshot Tool | Toolly.online', seoDescription: 'Capture site previews.', keywords: ['web screenshot'], rating: 4.8 },
  { id: 'file-conv', name: 'File Converter', slug: 'file-converter', category: 'Utility', icon: 'fa-file-export', description: 'Universal converter for documents and media.', seoTitle: 'Universal File Converter | Toolly.online', seoDescription: 'Convert file formats.', keywords: ['file converter'], rating: 4.6 },
  { id: 'yt-down', name: 'YouTube Downloader', slug: 'youtube-downloader', category: 'Social', icon: 'fa-video', description: 'Save your favorite videos for offline viewing.', seoTitle: 'YouTube Video Downloader | Toolly.online', seoDescription: 'Download YT content.', keywords: ['yt downloader'], rating: 4.9 },
  { id: 'vid-comp', name: 'Video Compressor', slug: 'video-compressor', category: 'Media', icon: 'fa-compress', description: 'Optimize video bitrate and resolution.', seoTitle: 'Video Compressor | Toolly.online', seoDescription: 'Shrink video files.', keywords: ['compress video'], rating: 4.5 }
];

export const CATEGORIES = ['All', 'AI', 'Media', 'Developer', 'Utility', 'Text', 'Social'] as const;
